spring:
  application:
    name: secure-server
  # monitoring configuration
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8443
  ssl:
    key-store: classpath:server-keystore.jks
    key-store-password: changeit
    key-alias: secure-server
    trust-store: classpath:server-truststore.jks
    trust-store-password: changeit
    enabled: true
    client-auth: need

endpoints:
  actuator:
    enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false
  trace:
    sensitive: false

logging:
  level:
    com.rdrcelic: debug