server:
  port: 8080

spring:
  application:
    name: mtls-client
  # monitoring configuration
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    sampler:
      percentage: 1.0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # to format timestamp in actuator endpoints

endpoints:
  actuator:
    enabled: true
  health:
    sensitive: false
  info:
    sensitive: false
  metrics:
    sensitive: false
  trace:
    sensitive: false

logging:
  level:
    com.rdrcelic: debug

hystrix:
  command:
    userServiceCommand:
      metrics:
        rollingStats:
          timeInMilliseconds: 100000
          numBuckets: 2
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 2
        errorThresholdPercentage: 50
        #sleepWindowInMilliseconds: 5000
  # calculate threadpool size after formula: (transactions_per_second * response_time) + buffer
  threadpool:
    UserService:
      coreSize: 50
      maxSize: 100


# actuator configuration
#management:
#  trace:
#    include: parameters,errors

